name: BedWars1058-WinStreak
version: '${project.version}'
main: com.reussy.exodus.bw1058winstreak.WinStreakPlugin
softdepend: [ BedWars1058, BedWarsProxy, PlaceholderAPI, BedWars1058-PrivateGames]
authors: [ reussy ]
api-version: 1.13
description: Win Streak system for BedWars players!
